Repository MicrosoftDocs/xamarin-docs.ko-kr, pull requests merged in 2018-12, with the labels that each got.

#21 Update index.md
  docs/xamarin-forms/get-started/hello-xamarin-forms-multiscreen/index.md
Labels: Accepted, Linguistics Suggestions

#15 Update installation.md
  docs/xamarin-forms/get-started/installation.md
Labels: Accepted, Linguistics Suggestions

#17 Update index.md
  docs/xamarin-forms/get-started/first-app/index.md
Labels: Accepted, Linguistics Suggestions

#18 Update index.md
  docs/xamarin-forms/get-started/hello-xamarin-forms/index.md
Labels: In Progress, Linguistics Suggestions

#40 Update xaml-previewer.md
  docs/xamarin-forms/xaml/xaml-previewer.md
Labels: Accepted, Linguistics Suggestions

#35 Update data-bindings-to-mvvm.md
  docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md
Labels: In Progress, Linguistics Suggestions

#14 Update index.md
  docs/xamarin-forms/get-started/index.md
Labels: Accepted, Linguistics Suggestions

#13 Update index.yml
  docs/xamarin-forms/index.yml
Labels: Accepted, Linguistics Suggestions

#30 Update xaml-markup-extensions.md
  docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md
Labels: Accepted, Linguistics Suggestions

#27 Update index.md
  docs/xamarin-forms/xaml/xaml-basics/index.md
Labels: In Progress, Linguistics Suggestions

#26 Update index.md
  docs/xamarin-forms/xaml/index.md
Labels: In Progress, Linguistics Suggestions

#24 Update deepdive.md
  docs/xamarin-forms/get-started/hello-xamarin-forms-multiscreen/deepdive.md
Labels: Linguistics Suggestions

#19 Update quickstart.md
  docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md
Labels: Accepted, Linguistics Suggestions

#42 Update index.md
  docs/xamarin-forms/xaml/markup-extensions/index.md
Labels: Linguistics Suggestions

#41 Update namespaces.md
  docs/xamarin-forms/xaml/namespaces.md
Labels: Linguistics Suggestions

#20 Update deepdive.md
  docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md
Labels: Accepted, Linguistics Suggestions

#16 Update docs/xamarin-forms/xaml/index.md
  docs/xamarin-forms/user-interface/animation/index.md
  docs/xamarin-forms/xaml/index.md
Labels: In Progress, Linguistics Suggestions

#47 Update field-modifiers.md
  docs/xamarin-forms/xaml/field-modifiers.md
Labels: Linguistics Suggestions

#45 Update creating.md
  docs/xamarin-forms/xaml/markup-extensions/creating.md
Labels: In Progress, Linguistics Suggestions

#25 Update introduction-to-xamarin-forms.md
  docs/xamarin-forms/get-started/introduction-to-xamarin-forms.md
Labels: Accepted, Linguistics Suggestions

#44 Update consuming.md
  docs/xamarin-forms/xaml/markup-extensions/consuming.md
Labels: Accepted, Linguistics Suggestions

#29 Update essential-xaml-syntax.md
  docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md
Labels: Accepted, Linguistics Suggestions

#43 Update user-interface/animation/simple.md
  docs/xamarin-forms/user-interface/animation/simple.md
Labels: Accepted, Linguistics Suggestions

#31 Update data-binding-basics.md
  docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md
Labels: Accepted, Linguistics Suggestions

#38 Update toolbox.md
  docs/xamarin-forms/xaml/toolbox.md
Labels: Accepted, Linguistics Suggestions
